name: amuse_app
description: A new Amuse application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dash_chat: ^1.1.15
  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  socket_io_client: ^0.9.11
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.5
  flutter_secure_storage: ^3.3.5
  fluttertoast: ^7.1.1
  cached_network_image: ^2.3.3
  flutter_dotenv: ^2.1.0
  dio: ^3.0.10
  pull_to_refresh: ^1.6.2
  carousel_slider: ^2.3.1
  smooth_page_indicator: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/icons/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Black.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Thin.otf
